// EZDRIVES — legal page content (bilingual).
// Chinese is the authored original; English is generated by the site's own
// translation chain (MyMemory zh-CN→en) — not hand-polished.

export interface LegalSection {
  title: { en: string; zh: string }
  body: { en: string; zh: string }
}

export interface LegalDoc {
  key: 'privacy' | 'terms' | 'cancellation'
  title: { en: string; zh: string }
  intro: { en: string; zh: string }
  sections: LegalSection[]
}

export const LEGAL_DOCS: LegalDoc[] = [
  {
    key: 'privacy',
    title: { en: 'Privacy Policy', zh: '隐私政策' },
    intro: {
      en: 'This Privacy Policy describes how EZDRIVES collects, uses and protects your personal information.',
      zh: '本隐私政策说明 EZDRIVES 如何收集、使用和保护您的个人信息。',
    },
    sections: [
      {
        title: { en: 'Information We Collect', zh: '我们收集的信息' },
        body: {
          en: 'Collected when registering: name, phone number, email, pick-up address. Collection at the time of appointment and payment: the time of the course appointment, payment method, and a screenshot of the payment voucher (only for the coach to check in).',
          zh: '注册时收集：姓名、手机号、邮箱、接送地址。预约与支付时收集：课程预约时间、支付方式、支付凭证截图（仅用于教练核对到账）。',
        },
      },
      {
        title: { en: 'USE OF INFORMATION', zh: '信息的使用' },
        body: {
          en: 'We only use your information to: schedule reminders, confirm payments, send course-related notifications, and improve our services. We do not sell your personal information to third parties.',
          zh: '我们仅将您的信息用于：安排与提醒课程、确认支付、发送课程相关通知、改进服务。我们不会向第三方出售您的个人信息。',
        },
      },
      {
        title: { en: 'Storage and protection of information', zh: '信息的存储与保护' },
        body: {
          en: 'The data is stored in a secure cloud database (Cloudflare D1). Passwords are hashed using PBKDF2, and clear-text passwords are never saved. A screenshot of the payment voucher is only visible to the coach.',
          zh: '数据存储于安全的云数据库（Cloudflare D1），密码使用 PBKDF2 加盐哈希存储，绝不保存明文密码。支付凭证截图仅教练可见。',
        },
      },
      {
        title: { en: 'YOUR RIGHTS', zh: '您的权利' },
        body: {
          en: 'You can edit your phone number, email, and pickup address at any time in your dashboard, or contact us to delete your account and data.',
          zh: '您可以随时在个人中心修改您的手机号、邮箱与接送地址；也可以联系我们删除您的账号与数据。',
        },
      },
      {
        title: { en: 'Contacts', zh: '联系方式' },
        body: {
          en: 'If you have a privacy-related question, please contact us through the contact information on the website.',
          zh: '如有隐私相关问题，请通过网站联系方式与我们联系。',
        },
      },
    ],
  },
  {
    key: 'terms',
    title: { en: 'Terms of Service', zh: '服务条款' },
    intro: {
      en: 'By booking a course with EZDRIVES, you agree to the following terms.',
      zh: '使用 EZDRIVES 预约课程即表示您同意以下条款。',
    },
    sections: [
      {
        title: { en: 'Appointments & Cancellations', zh: '预约与取消' },
        body: {
          en: 'Courses must be booked at least 24 hours in advance; same-day appointments are not available. If you need to cancel or reschedule, please do so at least 24 hours before the start of the course, otherwise it may affect subsequent appointments.',
          zh: '课程需提前至少 24 小时预约；当天不可预约。如需取消或改期，请在课程开始前至少 24 小时操作，否则可能影响后续预约。',
        },
      },
      {
        title: { en: 'Payment', zh: '支付' },
        body: {
          en: 'Cash, WeChat Pay, and Interac e-Transfer are supported. The order does not go into effect until the coach confirms it and unlocks the appointment; learners cannot mark the order as received on their own.',
          zh: '支持现金、微信支付与 Interac e-Transfer 三种方式。订单在教练确认到账后才生效并解锁预约；学员不能自行将订单标记为已到账。',
        },
      },
      {
        title: { en: 'Course Rules', zh: '课程规则' },
        body: {
          en: 'Package lessons are booked in the order of the lesson hours, with a maximum of about 2 consecutive lessons per day. Allow 15 minutes for breaks between different learners; the same learner can be connected.',
          zh: '套餐课程按课时顺序预约，每天最多连约 2 节。不同学员之间预留 15 分钟休息；同一学员可以连着上。',
        },
      },
      {
        title: { en: 'Responsibilities', zh: '责任' },
        body: {
          en: 'Coach is licensed and insured. Participants are required to comply with traffic laws and coaching instructions during the course; losses caused by the participants are borne by the participants.',
          zh: '教练持牌并投保。学员在课程中须遵守交通法规与教练指导；因学员原因造成的损失由学员承担。',
        },
      },
      {
        title: { en: 'Change', zh: '变更' },
        body: {
          en: 'We may update these Terms from time to time, and by continuing to use the Site after such updates, you will be deemed to have accepted them.',
          zh: '我们可能不时更新本条款，更新后继续使用本网站即视为接受。',
        },
      },
    ],
  },
  {
    key: 'cancellation',
    title: { en: '24-hour cancellation rule', zh: '24 小时取消规则' },
    intro: {
      en: "In order to ensure each learner's class schedule, we enforce the following cancellation and rescheduling rules.",
      zh: '为了保证每位学员的课时安排，我们执行以下取消与改期规则。',
    },
    sections: [
      {
        title: { en: 'Cancellations and rescheduling', zh: '取消与改期' },
        body: {
          en: 'Please cancel or reschedule at least 24 hours before the start of the course, which can be done through the My Courses page.',
          zh: '请在课程开始前至少 24 小时取消或改期，可通过「我的课程」页面操作。',
        },
      },
      {
        title: { en: 'Less than 24 hours', zh: '不足 24 小时' },
        body: {
          en: 'Cancellation or rescheduling less than 24 hours before the start of the lesson will be considered used and cannot be rescheduled.',
          zh: '课程开始前不足 24 小时取消或改期，该课时将视为已使用，无法重新安排。',
        },
      },
      {
        title: { en: 'Coach Reason Cancellation', zh: '教练原因取消' },
        body: {
          en: 'Courses canceled due to coaching reasons (vehicle breakdown, weather, etc.) will be rescheduled free of charge and will not take up your class time.',
          zh: '因教练原因（车辆故障、天气等）取消的课程将免费重新安排，不占用您的课时。',
        },
      },
      {
        title: { en: 'Not available on the day', zh: '当日不可约' },
        body: {
          en: 'Same day appointments are not allowed and coaches need time to prepare.',
          zh: '系统不允许预约当天课程，教练需要时间准备。',
        },
      },
    ],
  },
]
